// Apalabrar editor-bridge: TypeScript contract for the Rust+WASM editor core.
// The actual WASM bindings will be generated by wasm-bindgen and re-exported here.

export const VERSION = "0.0.0" as const;

export type DocId = string;
export type Position = number;

export type EditOp =
  | { kind: "InsertText"; at: Position; text: string }
  | { kind: "DeleteRange"; from: Position; to: Position };
